export { default as ButtButt } from './butt.png'
export { default as ScottFace } from './scott-face.jpg'
export { default as ScottMugFace } from './scott-mug-face.png'
export { default as Sparkles } from './sparkles.png'
export { default as TracedMugFace } from './traced-svg-scott-mug-face.svg'
