name: Generate Newsletter Draft
on:
  schedule:
    - cron: '0 9 1 * *' # 9am UTC on 1st of every month
  workflow_dispatch: # Manual trigger for testing

jobs:
  generate-newsletter:
    name: Generate newsletter from GitHub data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Generate newsletter via API
        run: |
          # Call production API to generate newsletter
          curl -X POST https://scottspence.com/api/ingest \
            -H "Content-Type: application/json" \
            -d '{"task": "generate_newsletter", "token": "${{ secrets.INGEST_TOKEN }}"}' \
            -o newsletter-response.json

          # Debug: Show the response
          echo "API Response:"
          cat newsletter-response.json
          echo ""

          # Extract content from JSON response
          CONTENT=$(cat newsletter-response.json | jq -r '.data.content')
          FILENAME=$(cat newsletter-response.json | jq -r '.data.filename')

          # Create newsletters directory if it doesn't exist
          mkdir -p content/newsletters

          # Save newsletter content to file
          echo "$CONTENT" > "content/newsletters/$FILENAME"

          echo "Newsletter saved to content/newsletters/$FILENAME"

      - name: Set newsletter date
        run: echo "NEWSLETTER_DATE=$(date +'%B %Y')" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message:
            "draft: newsletter for ${{ github.event.schedule ||
            'manual trigger' }}"
          branch: newsletters/draft-${{ github.run_number }}
          title: 'Newsletter Draft: ${{ env.NEWSLETTER_DATE }}'
          body: |
            # Newsletter Draft

            Generated by automated newsletter workflow.

            ## Instructions
            1. Review the newsletter content
            2. Edit as needed
            3. Set `published: true` in the frontmatter when ready
            4. Merge when satisfied

            ---

            _Generated by [generate-newsletter-draft workflow](.github/workflows/generate-newsletter-draft.yml)_
          delete-branch: true
