name: Generate Newsletter Draft
on:
  schedule:
    - cron: '0 9 1 * *' # 9am UTC on 1st of every month
  workflow_dispatch: # Manual trigger for testing

jobs:
  generate-newsletter:
    name: Generate newsletter from Bluesky + GitHub data
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4.2.0
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install tsx
        run: pnpm add -D tsx

      - name: Generate newsletter
        run: pnpx tsx scripts/generate-newsletter.ts
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message:
            "draft: newsletter for ${{ github.event.schedule ||
            'manual trigger' }}"
          branch: newsletters/draft-${{ github.run_number }}
          title: 'Newsletter Draft: ${{ github.run_id }}'
          body: |
            # Newsletter Draft

            Generated by automated newsletter workflow.

            ## Instructions
            1. Review the newsletter content
            2. Edit as needed
            3. Set `published: true` in the frontmatter when ready
            4. Merge when satisfied

            ---

            _Generated by [generate-newsletter-draft workflow](.github/workflows/generate-newsletter-draft.yml)_
          delete-branch: true
