name: Newsletter Reminder
on:
  schedule:
    - cron: '0 9 1 * *' # 9am UTC on 1st of every month
  workflow_dispatch: # Manual trigger for testing

jobs:
  create-reminder:
    name: Create newsletter reminder PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set newsletter date
        run: echo "NEWSLETTER_DATE=$(date +'%B %Y')" >> $GITHUB_ENV

      - name: Create reminder file
        run: |
          mkdir -p .github/newsletter-reminders
          cat > .github/newsletter-reminders/reminder-$(date +%Y-%m).md << 'EOF'
          # Newsletter Reminder for ${{ env.NEWSLETTER_DATE }}

          This is your monthly reminder to generate the newsletter!

          ## Steps

          ### 1. Generate Newsletter Locally

          Run this command in your terminal (make sure dev server is running):

          ```bash
          # Start dev server if not running
          pnpm dev

          # In another terminal, generate newsletter
          curl -X POST http://localhost:5173/api/ingest \
            -H "Content-Type: application/json" \
            -d '{"task": "generate_newsletter", "token": "your-token"}'
          ```

          This will create `content/newsletters/$(date +%Y-%m).md`

          ### 2. Review & Edit

          - Open the generated newsletter file
          - Review the content
          - Edit as needed
          - Add any additional sections

          ### 3. Publish

          When ready:
          - Set `published: true` in the frontmatter
          - Commit the newsletter file
          - Push to this PR branch
          - Merge the PR

          ### 4. Send Newsletter

          After merging, send via:

          ```bash
          curl -X POST http://localhost:5173/api/ingest \
            -H "Content-Type: application/json" \
            -d '{"task": "adhoc_newsletter_send", "token": "your-token"}'
          ```

          ---

          **Generated:** $(date)
          EOF

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: 'chore: newsletter reminder for ${{ env.NEWSLETTER_DATE }}'
          branch: newsletters/reminder-${{ github.run_number }}
          title: '📬 Newsletter Reminder: ${{ env.NEWSLETTER_DATE }}'
          body: |
            ## Monthly Newsletter Reminder

            Time to generate the newsletter for **${{ env.NEWSLETTER_DATE }}**!

            ### Quick Start

            1. **Start your dev server**: `pnpm dev`

            2. **Generate newsletter**:
            ```bash
            curl -X POST http://localhost:5173/api/ingest \
              -H "Content-Type: application/json" \
              -d '{"task": "generate_newsletter", "token": "your-token"}'
            ```

            3. **Review** the generated file at `content/newsletters/$(date +%Y-%m).md`

            4. **Edit** as needed, then set `published: true`

            5. **Commit and push** to this PR

            6. **Merge** when ready

            7. **Send newsletter**:
            ```bash
            curl -X POST http://localhost:5173/api/ingest \
              -H "Content-Type: application/json" \
              -d '{"task": "adhoc_newsletter_send", "token": "your-token"}'
            ```

            ---

            _Automated reminder by [newsletter workflow](.github/workflows/generate-newsletter-draft.yml)_
          delete-branch: true
          labels: newsletter
